### ISSUE TITLE
Create a bigger touch area for the menu icon

### ISSUE THREAD

**Issue by pimato** [ferni/makerdai.org#13]
Currently : 

<img width="765" alt="bildschirmfoto 2017-07-19 um 14 59 41" src="https://user-images.githubusercontent.com/5337809/28368334-49819038-6c94-11e7-9e2e-0ff14e2df2fa.png">

It could be much bigger on mobile so users don`t need to be so focused.

**Comment by ferni** [comment]
Solved by https://github.com/ferni/makerdai.org/pull/16
