### ISSUE TITLE
Get rid of links to # or preventDefault

### ISSUE THREAD

**Issue by ferni** [ferni/makerdai.org#17]
Some links make the page scroll to the top.

**Comment by peculiarity** [comment]
Well probably those links should actually point to something

**Comment by matttrichards** [comment]
@peculiarity there are alot of them there (like on the videos) that are shown on scroll over. We should just remove those I think.

**Comment by ferni** [comment]
Solved by https://github.com/ferni/makerdai.org/pull/50
