### ISSUE TITLE
Remove the hands from mobile version

### ISSUE THREAD

**Issue by pimato** [ferni/makerdai.org#27]
We need to keep it compact on mobile. It is far more important to keep the focus on the main video.
So we need to remove the hands. 

![img_1063](https://user-images.githubusercontent.com/5337809/28429690-e02bf4c6-6d7d-11e7-9d9d-6cb828d71832.png)

**Comment by matttrichards** [comment]
agreed


Matt

**Comment by go0t** [comment]
This zip contains:
https://we.tl/ecl5InUwUv

Video without the hands
Video without the coins + hands

**Comment by peculiarity** [comment]
Fixed in https://github.com/ferni/makerdai.org/pull/44
