### ISSUE TITLE
Headline & description

### ISSUE THREAD

**Issue by matttrichards** [ferni/makerdai.org#29]
"MakerDAO — Stability for the blockchain"
"Dai is a decentralized digital currency with stable value; the next step in the evolution of money."

**Comment by ferni** [comment]
Love the tagline.

**Comment by ferni** [comment]
So it's MakerDAO instead of Maker?

**Comment by matttrichards** [comment]
correct


Matt

**Comment by ferni** [comment]
@peculiarity why close the issue?

**Comment by ferni** [comment]
Done in https://github.com/ferni/makerdai.org/commit/4b29b32fcc98bbd2ead494b86f33d2ccb09c9c57
