### ISSUE TITLE
footer <p> alignment 

### ISSUE THREAD

**Issue by katherineobermeyer** [ferni/makerdai.org#42]
padding on the `<p>` tag causing the description to not line up with the "Discover and connect" 
![screen shot 2017-07-22 at 1 05 12 pm](https://user-images.githubusercontent.com/6266052/28493115-87e5bace-6ede-11e7-9aab-91bdb9b07d09.png)

**Comment by pimato** [comment]
@katherineobermeyer could you draw a line where exactly do you want to have the text ? I am removed the padding-top from the text and it looks worse in my view.

**Comment by go0t** [comment]
Visualization
![mkr-footer-p](https://user-images.githubusercontent.com/8461601/28509041-48ea7c80-6ff4-11e7-9788-ce8f9b6939e0.png)

**Comment by kennyrowe** [comment]
Should be fixed now
