### ISSUE TITLE
Update Main Nav - Remove Sentinel Link

### ISSUE THREAD

**Issue by kennyrowe** [ferni/makerdai.org#45]
Since we don't plan to use Sentinel Stake Voting we shouldn't highlight it.

Lets update the link with

Name: Road Map
Link: https://blog.makerdao.com/2016/12/02/2017-product-roadmap/

**Comment by ferni** [comment]
Done in https://github.com/ferni/makerdai.org/commit/c90fd10bfc428318b21b405806bbefc293f7625b
