### ISSUE TITLE
inputfield cutted off on mobile version

### ISSUE THREAD

**Issue by pimato** [ferni/makerdai.org#7]
Currently on every mobile version: 

<img width="358" alt="bildschirmfoto 2017-07-19 um 11 55 33" src="https://user-images.githubusercontent.com/5337809/28361734-fce0f062-6c79-11e7-8aac-b96fa910df26.png">

**Comment by peculiarity** [comment]
Hard to fix something that cannot be reproduced. If I cannot reproduce it then it might not be true that it's on every mobile version.

**Comment by matttrichards** [comment]
any progress on this?

**Comment by peculiarity** [comment]
YOu experience that problem as well ?

**Comment by matttrichards** [comment]
yes - in safari. I also just discovered that I get this rather bad formatting of the video in safari as well 

<img width="1273" alt="screen shot 2017-08-02 at 6 56 15 am" src="https://user-images.githubusercontent.com/16676712/28876996-e317c396-774f-11e7-9246-fbb2850a8c21.png">
<img width="1275" alt="screen shot 2017-08-02 at 6 56 02 am" src="https://user-images.githubusercontent.com/16676712/28876995-e317c9c2-774f-11e7-8bb0-8f02d54cb6f9.png">
